### ISSUE TITLE
Needs configuration for what url should be used when accessing the core API

### ISSUE THREAD

**Issue by Spetastian** [Kodkollektivet/owtf-valhalla-client#3]
A configuration object/file that the client is bundled with. Also the configuration should be easily mockable since we are using nock to mock responses from specific URL's when running unit tests.

**Comment by jherrlin** [comment]
As for now we have some problems with basic features of core on none Linux OSs.
The problem is that we have no chance of reach the containers from core or localhost, they are all adressed to only listen on the Docker network.
A solution for this problem may be to create portforwards for the containers, but that is a issue related to core. A solution for the client IP address could be to set up a remote core applicaiton while fixing the core issue.

**Comment by Spetastian** [comment]
Im not sure we are talking about the same thing here. In the client code i need a way to declare different URL's depending on how and where the code is runned.

Example:
Running in a container in production: The actual URL to the live Core API
Running locally in my dev env.: A same domain URL running localy that sends static JSON data just to have something to test the UI with.
Running my unit tests: The calls to a specific URL will be mocked here and therefor i need that URL to always be the one used by the internal API service wrapper when running the tests.

There are several ways to do this. The most common is to use a combination of enviromental variables and standard fallback values. This is not applicable here since the application will be built and bundled as a client side one page application.

I think the best way to do it is to have different build targets that gives different configuration values depending on wether you are building+bundling for devor for production.
